### ISSUE TITLE
Missing dependency check for as_tibble

### ISSUE THREAD

**Issue by hoehna** [cmt2/RevGadgets#2]
I just tried to read in some trees and got the following error:

Reading trees in file: output/Lampyridae_rooted_UCLN_run_1.trees
  |                                        |   0%Error in as_tibble(stats3) : could not find function "as_tibble"

**Comment by mikeryanmay** [comment]
This appears to be an issue on master but not on development. We're planning to merge development into master, right @cmt2?
If we're merging master into development, I think it might be safer to leave master as-is to reduce the potential for conflict.

**Comment by cmt2** [comment]
Yes - I'll do a master-development merge later this week. Just want to
finish up some stuff I'm working on with ancestral states beforehand.
*_______________*

*Carrie Malina Tribble <http://carrietribble.weebly.com>*
*Integrative Biology PhD Candidate at UC Berkeley*
*Williams College '13, Biology and Environmental Studies*
