### ISSUE TITLE
Assistance Required - "processDivRates" Function Outputting NA in Data Frame 

### ISSUE THREAD

**Issue by minghao-du** [cmt2/RevGadgets#27]
Dear RevGadgets Developers,

I am writing to report an issue I've encountered while using the "processDivRates" function in your software. It seems that the resulting data frame is not displaying the expected "fossilization rate" and "fossilization time" within the "item" column. Instead, these fields are populated with NA. 

Could you please provide some guidance or a potential fix for this issue? Your assistance would be greatly appreciated. 

<img width="650" alt="Figure_P1" src="https://github.com/revbayes/RevGadgets/assets/51898298/a6a8d3af-4676-41d4-b235-cdf6c6f7af24">
<img width="521" alt="Figure_P2" src="https://github.com/revbayes/RevGadgets/assets/51898298/245e6737-c18c-4b0e-b971-ad84c1026a43">
<img width="298" alt="Figure_P3" src="https://github.com/revbayes/RevGadgets/assets/51898298/d147e068-480d-4b2b-af39-def7c75e9988">

Best,
Minghao

**Comment by cmt2** [comment]
Dear Minghao, 

Thanks for bringing this to our attention. Could you please provide a working example (code and data) that recreates the issue? 

best,
Carrie

**Comment by minghao-du** [comment]
Hi Carrie,

Thank you for your prompt response. I am currently working through the Mass Extinction Estimation tutorial from the RevBayes Tutorials collection. Please note that this script requires the development version of RevBayes to function properly. For detailed information, please refer to my query posted on the RevBayes Users Forum: https://groups.google.com/g/revbayes-users/c/shztH9ovxcs. 

I have attached my modified RevBayes script for your reference. 
[mcmc_EFBD_mass_extinctions_modified.Rev.zip](https://github.com/revbayes/RevGadgets/files/13816891/mcmc_EFBD_mass_extinctions_modified.Rev.zip)

In addition, I am also including the incomplete log file from the last run to assist in diagnosing the issue. 
[Log-file.zip](https://github.com/revbayes/RevGadgets/files/13816962/Log-file.zip)

I have also uploaded the RevGadgets script that I have been using.
[processDivRates_Issue.zip](https://github.com/revbayes/RevGadgets/files/13816988/processDivRates_Issue.zip)

There might be a simpler way to pinpoint the problem. By duplicating the speciation_time_log and speciation_rate_log files from the RevGadgets example files and renaming the copies to fossilization_time_log and fossilization_rate_log, respectively, we might be able to replicate the issue more clearly.

I have encountered an additional issue when running the script. The new error reads as follows: 
Error in as.matrix(speciation_rate[, grepl("speciation", colnames(speciation_rate))]) -  :  non-conformable arrays 

I hope these files will help you pinpoint the problem. Please let me know if there is any other information I can provide. 

Best,
Minghao

**Comment by cmt2** [comment]
Hi Minghao,

Thanks for those files. I've just pushed an update to the development branch of RevGadgets. Could you try installing RevGadgets from development and see if the fix works for you? 

`devtools::install_github("revbayes/RevGadgets@development")`

**Comment by minghao-du** [comment]
Hi Carrie,

I am pleased to inform you that after using the development version of RevGadgets with the update you've provided, the issues I was facing have been resolved. Thank you very much for your timely and effective support. 

Your assistance has been invaluable, and I appreciate the effort you've put into addressing these concerns.

Best,
Minghao
