### ISSUE TITLE
readTrees for trees in Newick format

### ISSUE THREAD

**Issue by hoehna** [cmt2/RevGadgets#3]
Currently it seems that a single tree, e.g., a MAP or MCC tree, can only be read if it is in Nexus format. This type of checking might give problems. (1) There are traces that use Nexus files too (I think; you could ask Joel) and (2) when I transform the MAP tree by removing fossils, then I often store this tree simply as a Newick tree file. It would be nice to have an easy way to read these trees too.

**Comment by cmt2** [comment]
I just fixed readTrees() so it will read in a single newick string. @mikeryanmay - this fix changed your multiprocessing code from a while back. I have some ideas on how to add it back in that I'd like to run by you.

**Comment by siariazi** [comment]
Hi Carrie, I'm new to RevBayes and now I'm trying to use readTrees() function to read Newick formats. I just used the example provided here:
https://revbayes.github.io/documentation/readTrees.html
When I run this line on console: trees=readTrees(text="(a,(b,c));\n(d:0.1,(e:0.1,f:0.1):0.1);")
I get this error: "Error while converting Newick tree. We expected an opening parenthesis, but didn't get one."
Where is the problem?

**Comment by cmt2** [comment]
Hi @siariazi ! 

Thanks for your message. There are a few things going on here. The above github issue is related to RevGadgets, our R pacakge for processing RevBayes results, but it looks like you're talking about the RevBayes function (please correct me if I'm wrong). To be honest I'v never used readTrees() in RevBayes to read in trees using text strings before, and it seems that the text parser isn't the most reliable. I'd recommend reading trees in from text files. In general, the [tutorials](https://revbayes.github.io/tutorials) are a good way to get started with RevBayes. Here's a [tutorial](https://revbayes.github.io/tutorials/morph_ase/ase_mammals.html) the covers reading in a phylogeny from a file (among other things). If you have a specific need to read in trees using a text string, let me know and I can look into that aspect of the function. 

Hope this helps!

**Comment by siariazi** [comment]
Thanks @cmt2! Sorry to jump in your discussion. Yes I meant RevBayes itself; and I tried to read the same information from a file. It worked fine!
